<?php

/**
 * Implements hook_theme().
 */
function banner_theme($existing, $type, $theme, $path) {
    return array(
        'banner' => array(
            'variables' => array(
                'title_banner' => null,
                'body' => null,
                'one_button' => null,
                'two_button' => null,
                'three_button' => null
            ),
        )
    );
}
